language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sveluvil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sveluvil/docker-react npm run test