language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sveluvil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sveluvil/docker-react npm run test

deploy :
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  evn: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-731068111425"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY